/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend.vistas.Administracion;

import backend.controladores.ControladorUsuarioCliente;
import backend.enums.EstadoUsuarioCliente;
import backend.manejadores.Md5;
import backend.pojos.UsuarioCliente;
import java.sql.Date;

/**
 *
 * @author jes
 */
public class CambiarContrasenaDialog extends javax.swing.JDialog {

    private ControladorUsuarioCliente controladorUsuario;
    private UsuarioCliente user;

    /**
     * Creates new form CambiarContrasenaDialog
     */
    public CambiarContrasenaDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controladorUsuario = new ControladorUsuarioCliente();
        this.datosjEditorPane1.setContentType("text/html");
        this.user = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datosjEditorPane1 = new javax.swing.JEditorPane();
        buscarClientejButton1 = new javax.swing.JButton();
        cambiarContrasenajButton2 = new javax.swing.JButton();
        dpiTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Cambio de Contraseña");

        jLabel2.setText("DPI de cliente:");

        datosjEditorPane1.setEditable(false);
        jScrollPane1.setViewportView(datosjEditorPane1);

        buscarClientejButton1.setText("Buscar");
        buscarClientejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarClientejButton1ActionPerformed(evt);
            }
        });

        cambiarContrasenajButton2.setText("Cambiar contraseña");
        cambiarContrasenajButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarContrasenajButton2ActionPerformed(evt);
            }
        });

        dpiTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dpiTextField1KeyTyped(evt);
            }
        });

        jButton1.setText("Nueva busqueda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(263, 263, 263))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(dpiTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buscarClientejButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(593, Short.MAX_VALUE)
                    .addComponent(cambiarContrasenajButton2)
                    .addGap(59, 59, 59)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(buscarClientejButton1)
                    .addComponent(dpiTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(338, Short.MAX_VALUE)
                    .addComponent(cambiarContrasenajButton2)
                    .addGap(63, 63, 63)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarClientejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarClientejButton1ActionPerformed
        String dpi = this.dpiTextField1.getText();
        this.user = controladorUsuario.buscarUsuarioCliente(dpi, EstadoUsuarioCliente.ACTIVADO);
        if (user != null) {
            mostrarInformacionDeSolicitud(user);
        } else {
            mostrarMensajeDeInformacionNoEncontrada();
        }
    }//GEN-LAST:event_buscarClientejButton1ActionPerformed

    private void cambiarContrasenajButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarContrasenajButton2ActionPerformed
        if (user != null) {
            String contrasena = ControladorUsuarioCliente.generarContrasena();
            String contrasenaEncriptada =Md5.getMD5(contrasena);
            Date fechaCaducidad =user.generarFechaDeCaducidad();
            controladorUsuario.modificarContrasena(user.getDpiCliente(), contrasenaEncriptada,fechaCaducidad);
            //Mandar correo
            controladorUsuario.notificarCambioDeContrasena(contrasena, user.getEmail(), fechaCaducidad, user.getUsuarioCliente());
            //Mensaje de aprobacion
            mostrarMensajeDeCambioDeContrasena();
            user = null;
        } else {
            mostrarMensajeDeUsuarioNoEscogido();
            this.dpiTextField1.setText("");
        }
    }//GEN-LAST:event_cambiarContrasenajButton2ActionPerformed

    private void dpiTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dpiTextField1KeyTyped

        char caracter = evt.getKeyChar();

        // Verificar si la tecla pulsada no es un digito
        if (dpiTextField1.getText().length() == 13) {
            evt.consume();
        } else {
            if (((caracter < '0')
                    || (caracter > '9'))
                    && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
                evt.consume();  // ignorar el evento de teclado
            }

        }

    }//GEN-LAST:event_dpiTextField1KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dpiTextField1.setText("");
        this.datosjEditorPane1.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarClientejButton1;
    private javax.swing.JButton cambiarContrasenajButton2;
    private javax.swing.JEditorPane datosjEditorPane1;
    private javax.swing.JTextField dpiTextField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void mostrarInformacionDeSolicitud(UsuarioCliente cliente) {
        this.datosjEditorPane1.setText(
                "<h5><p style=\"color:green;\">USUARIO ENCONTRADO</p></h5>"
                + "<ul>\n"
                + "  <li>DPI: " + cliente.getDpiCliente() + "</li>\n"
                + "  <li>Estado: " + cliente.getEstado().toString() + "</li>\n"
                + "  <li>Id usuario: " + cliente.getUsuarioCliente() + "</li>\n"
                + "  <li>CORREO: " + cliente.getEmail() + "</li>\n"
                + "</ul>"
        );
    }

    private void mostrarMensajeDeInformacionNoEncontrada() {
        this.datosjEditorPane1.setText(
                "<ul>\n"
                + "  <li>   <p style=\"color:#FF0000\";>NO SE ENCONTRO AL USUARIO</p></li>\n"
                + "</ul>"
        );
    }

    private void mostrarMensajeDeUsuarioNoEscogido() {
        this.datosjEditorPane1.setText(
                "<ul>\n"
                + "  <li>   <p style=\"color:#FF0000\";>NO HA BUSCADO UN USUARIO</p></li>\n"
                + "</ul>"
        );
    }

    private void mostrarMensajeDeCambioDeContrasena() {
        this.datosjEditorPane1.setText(
                "<h5><p style=\"color:green;\">Contrasena cambiada</p></h5>"
                + "<ul>\n"
                + "  <li>DPI: " + user.getDpiCliente() + "</li>\n"
                + "  <li>Estado: " + EstadoUsuarioCliente.NUEVO.toString() + "</li>\n"
                + "</ul>"
                + "<h5><p style=\"color:black;\">La informacion se ha enviado por correo electronico</p></h5>"
        );
    }

}
