
/*PROCEDIMIENTO PARA CAMBIAR EL SALDO DE UNA CUENTA, CUANDO SE HA REALIZADO UN MOVIMIENTO BANCARIO*/

DELIMITER $$
DROP PROCEDURE IF EXISTS actualizarSaldoCuenta;
create procedure actualizarSaldoCuenta(in tipo VARCHAR(10), in monto double , in noCuenta VARCHAR(10))
BEGIN 
IF tipo='ABONO' THEN
UPDATE CUENTA SET SALDO=SALDO+monto  WHERE NO_CUENTA_BANCARIA=noCuenta;

ELSE 
UPDATE CUENTA SET SALDO=SALDO-monto  WHERE NO_CUENTA_BANCARIA=noCuenta;
END IF;

END;

$$
DELIMITER ;


/*PROCEDIMIENTO PARA REGISTRAR EL SALDO INICIAL DE UNA CUENTA AL MOMENTO DE CREARSE, Y QUEDE REGISTRADO EN MOVIMIENTO MONETARIO*/


DELIMITER $$
DROP PROCEDURE IF EXISTS crearMovimientoMonetarioInicialCuenta;
create procedure crearMovimientoMonetarioInicialCuenta(in noCuenta VARCHAR(10), in monto double)
BEGIN 
INSERT INTO MOVIMIENTO_MONETARIO VALUES(null,noCuenta,monto,CURRENT_TIMESTAMP,'ABONO');
END;

$$
DELIMITER ;





